import sys
sys.path.insert(0, '.')
from api.scan import TICKERS as BASE

EXTRA = [
    "BHEL.NS","BEL.NS","HAL.NS","IRFC.NS","PFC.NS","RECLTD.NS","GAIL.NS",
    "SAIL.NS","NMDC.NS","AMBUJACEM.NS","PNB.NS","BANKBARODA.NS","CANBK.NS",
    "DLF.NS","GODREJCP.NS","DABUR.NS","COLPAL.NS","MARICO.NS","PIDILITIND.NS",
    "HAVELLS.NS","VOLTAS.NS","SIEMENS.NS","ABB.NS","CUMMINSIND.NS","ASHOKLEY.NS",
    "TVSMOTOR.NS","TATACOMM.NS","PERSISTENT.NS","COFORGE.NS","MPHASIS.NS",
    "SRF.NS","ASTRAL.NS","DIXON.NS","POLYCAB.NS","TATAPOWER.NS",
    "ATGL.NS","PETRONET.NS","INDHOTEL.NS","CHOLAFIN.NS","MUTHOOTFIN.NS",
    "IDFCFIRSTB.NS","BANDHANBNK.NS","FEDERALBNK.NS","RBLBANK.NS","AUBANK.NS",
    "JIOFIN.NS","LODHA.NS","VEDL.NS","SHRIRAMFIN.NS","HDFCAMC.NS",
    "NIPPONLIFE.NS","ICICIPRAMC.NS","UTIAMC.NS","NAUKRI.NS","DMART.NS",
    "AUROPHARMA.NS","LUPIN.NS","ALKEM.NS","TORNTPHARM.NS","IPCALAB.NS",
    "LALPATHLAB.NS","METROPOLIS.NS","FORTIS.NS","MAXHEALTH.NS",
    "GLAXO.NS","PFIZER.NS","ABBOTINDIA.NS","SANOFI.NS","NATCOPHARMA.NS",
    "POLYMED.NS","APOLLOHOSP.NS","AARTIIND.NS","GRANULES.NS","GLENMARK.NS",
    "BIOCON.NS","AJANTPHARM.NS","JBCHEPHARM.NS","ERIS.NS","LAURUSLABS.NS",
    "STRIDES.NS","SOLARA.NS","SEQUENT.NS","SUVEN.NS","NEULANDLAB.NS",
    "LTTS.NS","CYIENT.NS","KPITTECH.NS","TATAELXSI.NS",
    "RATEGAIN.NS","TANLA.NS","INTELLECT.NS","MASTEK.NS","ZENSAR.NS",
    "NIITTECH.NS","HEXAWARE.NS","BIRLASOFT.NS","SONATSOFTW.NS","HINDWARE.NS",
    "CMSINFO.NS","ECLERX.NS","NUCLEUS.NS","DATAMATICS.NS","FIRSTSOURCE.NS",
    "EXIDEIND.NS","MOTHERSON.NS","BOSCHLTD.NS","BHARATFORG.NS",
    "SUNDRMFAST.NS","MINDAIND.NS","GABRIEL.NS","CRAFTSMAN.NS","PRICOL.NS",
    "ENDURANCE.NS","SUPRAJIT.NS","MINDA.NS","SUBROS.NS","LUMAXTECH.NS",
    "TIINDIA.NS","GREENPANEL.NS","SCHAEFFLER.NS","SKFINDIA.NS","TIMKEN.NS",
    "CESC.NS","TORNTPOWER.NS","INOXWIND.NS","SUZLON.NS","THERMAX.NS",
    "KPIL.NS","NCC.NS","NBCC.NS","RVNL.NS","IRCON.NS","RITES.NS",
    "RAILVIKAS.NS","GRINFRA.NS","PNCINFRATECH.NS","HGINFRA.NS",
    "AHLUCONT.NS","PSP.NS","KNRCON.NS","HCC.NS","CAPACITE.NS",
    "GPPL.NS","JMFINANCIAL.NS","ENGINERSIN.NS","BHEL.NS","POWMECH.NS",
    "RADICO.NS","VARUN.NS","VBLLTD.NS","UNITDSPR.NS",
    "JYOTHYLAB.NS","EMAMILTD.NS","BAJAJCONS.NS","HATSUN.NS",
    "PGHH.NS","BERGEPAINT.NS","KANSAINER.NS","AKZONOBEL.NS",
    "SUPREMEIND.NS","APLAPOLLO.NS","HERITGFOOD.NS","AGRO.NS",
    "HINDZINC.NS","NATIONALUM.NS","MOIL.NS","AIAENG.NS","RATNAMANI.NS",
    "MAHSEAMLES.NS","MIDHANI.NS","WELSPUNIND.NS","JSWENERGY.NS",
    "NSLNISP.NS","TINPLATE.NS","GMRINFRA.NS","APL.NS","SSWL.NS",
    "GODREJPROP.NS","PRESTIGE.NS","PHOENIX.NS","BRIGADE.NS","SOBHA.NS",
    "OBEROIRLTY.NS","KOLTEPATIL.NS","MAHLIFE.NS","SUNTECK.NS",
    "RAMCOCEM.NS","DALMIA.NS","HEIDELBERG.NS","JKCEMENT.NS","STARCEMENT.NS",
    "ORIENTCEM.NS","BIRLACORPN.NS","JKPAPER.NS","TNPL.NS",
    "DEEPAKNITR.NS","GNFC.NS","ALKYLAMINE.NS","VINATIORGA.NS","NAVINFLUOR.NS",
    "FLUOROCHEM.NS","PCBL.NS","AAVAS.NS","TATACHEM.NS",
    "BALAMINES.NS","FINEORG.NS","GALAXYSURF.NS","NOCIL.NS",
    "GHCL.NS","ATUL.NS","SUDARSCHEM.NS","HFCL.NS","LXCHEM.NS",
    "ABCAPITAL.NS","CHOLAHLDNG.NS","PNBHOUSING.NS","LICHSGFIN.NS",
    "MANAPPURAM.NS","BAJAJHFL.NS","UJJIVANSFB.NS","EQUITASBNK.NS",
    "ESAFSFB.NS","CSBBANK.NS","SURYODAY.NS","KARURVYSYA.NS","DCBBANK.NS",
    "INDIAMART.NS","ANGELONE.NS","IIFL.NS","MOFSL.NS","IREDA.NS",
    "INDUSTOWER.NS","TTML.NS","TEJASNET.NS","SAREGAMA.NS","SUNTV.NS","PVRINOX.NS",
    "BLUEDART.NS","TCI.NS","CONCOR.NS","ALLCARGO.NS",
    "NYKAA.NS","PAYTM.NS","JUBLFOOD.NS","WESTLIFE.NS","DEVYANI.NS",
    "APOLLOTYRE.NS","MRF.NS","CEATLTD.NS","BALKRISIND.NS",
    "BATAINDIA.NS","RELAXO.NS","VMART.NS","SHOPERSTOP.NS",
    "SPARC.NS","WOCKPHARMA.NS","SYNGENE.NS","SUNTV.NS","NETWORK18.NS",
    "ZEEL.NS","EDELWEISS.NS","MOTILALOFS.NS",
    "JSWINFRA.NS","ADANIGREEN.NS","ADANIPOWER.NS","ADANITRANS.NS","AWL.NS",
    "POLICYBZR.NS","ROUTE.NS","CDSL.NS","BSE.NS","MCX.NS","CAMS.NS",
    "KFINTECH.NS","MAPMYINDIA.NS",
    "BPCL.NS","IOC.NS","HINDPETRO.NS","MRPL.NS","CPCL.NS",
    "OIL.NS","MGL.NS","IGL.NS","GSPL.NS",
    "SJVN.NS","NHPC.NS","BEML.NS","HUDCO.NS","REC.NS",
]

FULL = list(dict.fromkeys(BASE + EXTRA))
print(f"Base tickers (Vercel):  {len(BASE)}")
print(f"Extra tickers (local):  {len(EXTRA)}")
print(f"TOTAL UNIQUE (deduped): {len(FULL)}")
print()
print("All tickers:")
for i, t in enumerate(FULL, 1):
    print(f"  {i:3}. {t.replace('.NS','')}")
